# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('ingredients', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
    ]
